apiVersion: v1
kind: Service
metadata:
  name: partie-web-app
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: partie-web-app

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: partie-web-app
spec:
  replicas: <%replicas%>
  template:
    metadata:
      labels:
        app: partie-web-app
    spec:
      containers:
      - name: partie-web-app
        image: <%image-name%>
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "<%env_ASPNETCORE_ENVIRONMENT%>"
        - name: SSLCertPass
          value: "<%SSLCertPass%>"
        - name: ApplicationInsights__InstrumentationKey
          value: "<%ApplicationInsightsInstrumentationKey%>"
        - name: Auth__AuthServerUrl
          value: "<%env_Auth__AuthServerUrl%>"
        - name: WebAppUrl
          value: "<%env_WebAppUrl%>"
        - name: GatewayApiUrl
          value: "<%env_GatewayApiUrl%>"
        - name: AgeLimit
          value: "<%env_AgeLimit%>"
        - name: Recaptcha__SiteKey
          value: "<%env_Recaptcha__SiteKey%>"
        - name: CdnBaseUrl
          value: "<%env_CdnBaseUrl%>"
        - name: ChatApiUrl
          value: "<%env_ChatApiUrl%>"
        - name: CommApiUrl
          value: "<%env_CommApiUrl%>"        
        readinessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 7

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: web-app-ingress
spec:
  rules:
    - host: <%subdomain%>.partie.com
      http:
        paths:
          - backend:
              serviceName: partie-web-app
              servicePort: 443
            path: /
  tls:
    - hosts:
        - <%subdomain%>.partie.com
      secretName: aks-partie-tls